### ISSUE TITLE
Unexpected ',' error when trying to use gem.

### ISSUE THREAD

**Issue by boboTjones** [discourse/discourse_api#114]
I see the following error when trying to start the server, in irb and when running rake tasks. Please advise.

```
irb(main):001:0> require 'discourse_api'
SyntaxError: /Library/Ruby/Gems/2.0.0/gems/discourse_api-0.10.1/lib/discourse_api/api/posts.rb:31: syntax error, unexpected ','
      def destroy_post_action(post_id:, post_action_type_id:)
                                       ^
/Library/Ruby/Gems/2.0.0/gems/discourse_api-0.10.1/lib/discourse_api/api/posts.rb:36: syntax error, unexpected ','
      def post_action_users(post_id:, post_action_type_id:)
                                     ^
/Library/Ruby/Gems/2.0.0/gems/discourse_api-0.10.1/lib/discourse_api/api/posts.rb:41: syntax error, unexpected keyword_end, expecting end-of-input
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/discourse_api-0.10.1/lib/discourse_api/client.rb:10:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /Library/Ruby/Gems/2.0.0/gems/discourse_api-0.10.1/lib/discourse_api.rb:2:in `<top (required)>'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
    from (irb):1
    from /usr/bin/irb:12:in `<main>'
irb(main):002:0> 
```

**Comment by ZogStriP** [comment]
What version of ruby are you using?

**Comment by boboTjones** [comment]
```
erin$ bundle exec rails --version
Warning: You're using Rubygems 2.0.14 with Spring. Upgrade to at least Rubygems 2.1.0 and run `gem pristine --all` for better startup performance.
Rails 4.2.1
```

**Comment by boboTjones** [comment]
OS X 10.10.5 default. 
```
bundle exec ruby --version
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
```

**Comment by tarcieri** [comment]
@ZogStriP if your gem requires ruby 2.1 at a minimum, you should really add the following to your gemspec:

```ruby
spec.required_ruby_version = '>= 2.1'
```

**Comment by SamSaffron** [comment]
sure seems reasonable to add, though very odd not to support 2.0 here.
